services:
  mysql:
    image: mysql:8.4
    container_name: gymcontrol-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gymcontrol
      MYSQL_USER: gymcontrol
      MYSQL_PASSWORD: gymcontrol

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
